analytics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: admin
      password: admin
      port: 5432
      dbname: analytics
      schema: staging
      threads: 4
